In [1]:
import numpy as np

In [2]:
haha = np.zeros((3,5,6))
a = np.zeros((5,6))
b = np.ones((5,5))
lis = []
lis.append(a)
lis.append(b)
haha[0] = a
haha[1] = b
print(haha)

ValueError: could not broadcast input array from shape (5,5) into shape (5,6)

In [ ]:
aaa = np.load("../data/features/audio_feature.npy")

In [ ]:
import random
a = random.sample(set([1, 2]), 2)
print(a)

In [ ]:
print(random.randint(0,10))

In [9]:
import cv2
a = np.zeros((1,16,112,112,3),dtype=np.uint8)
path = "../data/extract_result/8207_keyframe_"
for i in range(16):
    ttt = cv2.imread(path + str(i) + ".jpg")
    a[0][i]=ttt
print(a)


[[[[[ 23  25  26]
    [ 23  25  26]
    [ 25  25  25]
    ...
    [ 27  25  25]
    [ 25  25  25]
    [ 25  25  25]]

   [[ 23  25  26]
    [ 23  25  26]
    [ 25  25  25]
    ...
    [ 27  25  25]
    [ 25  25  25]
    [ 25  25  25]]

   [[ 23  25  26]
    [ 23  25  26]
    [ 25  25  25]
    ...
    [ 27  25  25]
    [ 25  25  25]
    [ 25  25  25]]

   ...

   [[ 25  25  25]
    [ 25  25  25]
    [ 25  25  25]
    ...
    [ 25  25  25]
    [ 25  25  25]
    [ 25  25  25]]

   [[ 25  25  25]
    [ 25  25  25]
    [ 25  25  25]
    ...
    [ 25  25  25]
    [ 25  26  24]
    [ 25  26  24]]

   [[ 25  25  25]
    [ 25  25  25]
    [ 25  25  25]
    ...
    [ 25  25  25]
    [ 25  26  24]
    [ 25  26  24]]]


  [[[ 25  25  25]
    [ 25  25  25]
    [ 25  25  25]
    ...
    [ 25  25  25]
    [ 25  25  25]
    [ 25  25  25]]

   [[ 25  25  25]
    [ 25  25  25]
    [ 25  25  25]
    ...
    [ 25  25  25]
    [ 25  25  25]
    [ 25  25  25]]

   [[ 25  25  25]
    [ 25  25  25]
    [ 25  

In [37]:
nn = np.load("../data/features/video_feature.npy")
nn.shape

(2, 4096)

In [16]:
haha = np.random.random((5,10))
haha

array([[0.92239142, 0.63752168, 0.8723046 , 0.37586822, 0.93240077,
        0.13643338, 0.57266884, 0.47965237, 0.98768857, 0.19399802],
       [0.28671036, 0.8570478 , 0.41872389, 0.84081027, 0.5489653 ,
        0.53462023, 0.06055276, 0.55193522, 0.04404968, 0.24397932],
       [0.22475283, 0.89794029, 0.67683918, 0.71362958, 0.16101695,
        0.14222469, 0.87278751, 0.72553141, 0.88456263, 0.78012264],
       [0.0885636 , 0.25815897, 0.48260497, 0.80369285, 0.0016321 ,
        0.13279885, 0.38027498, 0.58788636, 0.45497192, 0.33269169],
       [0.4120131 , 0.93486401, 0.94549515, 0.22424986, 0.51513926,
        0.78120743, 0.91905125, 0.09966209, 0.51028826, 0.68104843]])