In [1]:
import numpy as np

In [2]:
haha = np.zeros((3,5,6))
a = np.zeros((5,6))
b = np.ones((5,5))
lis = []
lis.append(a)
lis.append(b)
haha[0] = a
haha[1] = b
print(haha)

ValueError: could not broadcast input array from shape (5,5) into shape (5,6)

In [ ]:
aaa = np.load("../data/features/audio_feature.npy")

In [ ]:
import random
a = random.sample(set([1, 2]), 2)
print(a)

In [ ]:
print(random.randint(0,10))

In [ ]:
import cv2
a = np.zeros((1,16,112,112,3),dtype=np.uint8)
path = "../data/extract_result/8207_keyframe_"
for i in range(16):
    ttt = cv2.imread(path + str(i) + ".jpg")
    a[0][i]=ttt
print(a)


In [ ]:
nn = np.load("../data/features/video_feature.npy")
nn.shape

In [ ]:
haha = np.random.random((5,10))
haha

In [3]:
'''
data:数据集
test_ratio:测试机占比
如果data为numpy.numpy.ndarray直接使用此代码
如果data为pandas.DatFrame类型则
    return data[train_indices],data[test_indices]
修改为
    return data.iloc[train_indices],data.iloc[test_indices]
'''
def split_train(data,test_ratio):
    np.random.seed(43)
    shuffled_indices=np.random.permutation(len(data))
    test_set_size=int(len(data)*test_ratio)
    test_indices =shuffled_indices[:test_set_size]
    train_indices=shuffled_indices[test_set_size:]
    return data[train_indices],data[test_indices]

In [4]:
data=np.random.randint(100,size=[25,4])
print(data)

[[ 5  3 93 86]
 [16 72 21 35]
 [56 54  3 64]
 [19 16 55 43]
 [ 6  7 26 33]
 [22  6 13 17]
 [41 22 82 77]
 [31 47 97 48]
 [54 36 40 26]
 [21 26 10 56]
 [59 65 16 76]
 [99 85 96 27]
 [79 98 47 87]
 [22 72 20 59]
 [55  0  3 79]
 [97 23 22 22]
 [74 16 72 35]
 [34 56 33 49]
 [52 74 66 34]
 [79 53  1 71]
 [ 5 45 82 11]
 [41 83 31 61]
 [ 3 88 40  8]
 [52 95 62 12]
 [39 79  4 72]]


In [11]:
aaa = split_train(data, 0.2)
print(len(aaa[0]), len(aaa[1]))

20 5
