In [1]:
import numpy as np
import pandas as pd
hetrec_path = "F:\data\hetrec2011-movielens-2k-v2\\"

In [2]:
# file=open('../data/testMovieID.txt', 'r')
file=open('../data/movieID.txt', 'r')
movieID = [int(x.strip()) for x in file]
file.close()

In [3]:
df_country = pd.read_table(hetrec_path+"movie_countries.dat",index_col="movieID")
df_country = df_country.fillna("UNKNOWN")

In [4]:
countries = []
for id in movieID:
    tmp = df_country.get_value(id, "country")
    countries.append(tmp)
print(countries)

['USA', 'USA', 'USA', 'USA', 'USA', 'Iran', 'USA', 'Netherlands', 'USA', 'USA', 'USA', 'USA', 'USA', 'New Zealand', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'France', 'USA', 'UK', 'USA', 'USA', 'USA', 'USA', 'Argentina', 'Hungary', 'USA', 'USA', 'USA', 'New Zealand', 'USA', 'USA', 'USA', 'UK', 'USA', 'USA', 'UK', 'France', 'Canada', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'France', 'USA', 'France', 'West Germany', 'Portugal', 'UK', 'USA', 'USA', 'UK', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'USA', 'USA', 'France', 'USA', 'China', 'Hong Kong', 'USA', 'USA', 'USA', 'USA', 'Vietnam', 'USA', 'USA', 'Australia', 'USA', 'Germany', 'Hong Kong', 'USA', 'USA', 'UK', 'USA', 'USA', 'Australia', 'France', 'USA', 'USA', 'Hong Kong', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'USA', 'France', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA',

c:\users\wang\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  after removing the cwd from sys.path.


In [5]:
countryID = list(set(countries))
countryID.sort()

In [6]:
id = [i for i in range(len(countryID))]
iddict = dict(zip(countryID, id))
print(iddict)


{'Argentina': 0, 'Australia': 1, 'Austria': 2, 'Canada': 3, 'China': 4, 'Colombia': 5, 'Denmark': 6, 'East Germany': 7, 'Finland': 8, 'France': 9, 'Germany': 10, 'Hong Kong': 11, 'Hungary': 12, 'India': 13, 'Iran': 14, 'Ireland': 15, 'Italy': 16, 'Japan': 17, 'Mexico': 18, 'Netherlands': 19, 'New Zealand': 20, 'Poland': 21, 'Portugal': 22, 'Republic of Macedonia': 23, 'Romania': 24, 'Russia': 25, 'South Korea': 26, 'Soviet Union': 27, 'Spain': 28, 'Sweden': 29, 'Switzerland': 30, 'Taiwan': 31, 'UK': 32, 'UNKNOWN': 33, 'USA': 34, 'Vietnam': 35, 'West Germany': 36}


In [7]:
code = np.zeros((len(countries), len(countryID)), dtype=int)
tmp = 0
for name in countries:
    code[tmp][iddict.get(name)] = 1
    tmp += 1

In [8]:
file = open("../data/countryID.txt", "w")
tmp = 0
for name in countryID:
    file.write(str(tmp) + "," + name + "\n")
    tmp += 1
file.close()

In [9]:
np.save("../data/features/country_feature.npy", code)

上面是国家特征向量，下面如法炮制类别特征<br>
国家是一对一，类别是多对一，需要修改

In [46]:
df_genre = pd.read_table(hetrec_path+"movie_genres.dat")
df_genre = df_genre.fillna("UNKNOWN")

In [49]:
genre_name = set()
genres_list = []
for id in movieID:
    tmp = df_genre[df_genre.movieID == id]["genre"]
    genres_list.append(list(tmp))
    genre_name |= set(tmp)
genre_name = list(genre_name)
genre_name.sort()
print(genre_name)
print(genres_list)

['Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'IMAX', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
[['Comedy', 'Romance'], ['Adventure', 'Children'], ['Action'], ['Drama'], ['Drama', 'Thriller'], ['Children', 'Drama'], ['Crime', 'Drama', 'Romance'], ['Comedy', 'Drama'], ['Drama'], ['Comedy', 'Drama'], ['Drama', 'Romance'], ['Adventure', 'Drama'], ['Children', 'Comedy'], ['Comedy'], ['Action', 'Thriller'], ['Drama'], ['Drama', 'Horror', 'Thriller'], ['Comedy', 'Romance'], ['Comedy', 'Drama', 'Romance'], ['Action', 'Adventure', 'Thriller'], ['Comedy', 'Drama'], ['Drama'], ['Action', 'Thriller'], ['Documentary'], ['Comedy', 'Thriller'], ['Comedy'], ['Action', 'Drama', 'Thriller'], ['Comedy', 'Fantasy', 'Romance', 'Sci-Fi'], ['Drama'], ['Fantasy'], ['Drama'], ['Drama'], ['Action', 'Adventure', 'Drama', 'Thriller'], ['Comedy', 'Horror', 'Thriller'], ['Drama'], ['Children', 'Comedy'], 

In [48]:
id = [i for i in range(len(genre_name))]
iddict = dict(zip(genre_name, id))
print(iddict)

{'Action': 0, 'Adventure': 1, 'Animation': 2, 'Children': 3, 'Comedy': 4, 'Crime': 5, 'Documentary': 6, 'Drama': 7, 'Fantasy': 8, 'Film-Noir': 9, 'Horror': 10, 'IMAX': 11, 'Musical': 12, 'Mystery': 13, 'Romance': 14, 'Sci-Fi': 15, 'Thriller': 16, 'War': 17, 'Western': 18}


In [51]:
code = np.zeros((len(movieID), len(genre_name)), dtype=int)
tmp = 0
for names in genres_list:
    for name in names:
        code[tmp][iddict.get(name)] = 1
    tmp += 1
print(code)

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [52]:
file = open("../data/genreID.txt", "w")
tmp = 0
for name in genre_name:
    file.write(str(tmp) + "," + name + "\n")
    tmp += 1
file.close()

In [54]:
np.save("../data/features/genre_feature.npy", code)